---
- name: Download the artifact
  maven_artifact:
    group_id: in.shan5a6
    artifact_id: myweb
    repository_url: 'http://18.234.149.107/repository/app1-artifactory/'
    extension: war
    version: "{{ artifact_version }}"
    username: "{{ nexus_user }}"
    password: "{{ nexus_password }}"
    dest: /opt/tomcat/webapps/

